name: Publish
on:
    push:
        paths:
            - setup.py
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - run: |
                pip install twine
                python setup.py sdist
            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                user: ${{ secrets.PYPI_USER}}
                password: ${{ secrets.PYPI_PASSWORD}}
                skip-existing: true
                print-hash: true